01. Web (UI)/GestionPruebas.Web/Controllers/AspiranteController.cs
#nullable disable
using System.Net.Http.Headers;
using System.Net.Mime;
using System.Text;
using System.Text.Json;
using GestionPruebas.Web.Helper;
using GestionPruebas.Web.Models.Dto;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList;


namespace GestionPruebas.Web.Controllers
{
    public class AspiranteController : Controller
    {
        private readonly ILogger<AspiranteController> _logger;
        private readonly IHttpClientFactory _clientFactory;
        private readonly IConfiguration _configuration;

        public AspiranteController(ILogger<AspiranteController> logger, IHttpClientFactory httpClientFactory, IConfiguration configuration)
        {
            _logger = logger;
            _clientFactory = httpClientFactory;
            _configuration = configuration;

        }
        public async Task<IActionResult> Index(int? page)
        {
            int pageNumber = page ?? 1;
            int pageSize = 10; 

            AspiranteResponseDto model = await GetAspirantesAsync();
            var pagedList = await model.aspirantes.ToPagedListAsync(pageNumber, pageSize);

            IPagedList<AspiranteDto> pagedAspirantes = new StaticPagedList<AspiranteDto>(pagedList.ToList(), pagedList.GetMetaData());

            return View(pagedAspirantes);
        }

        [HttpGet]
        [Authorize]
        public async Task<AspiranteResponseDto> GetAspirantesAsync()
        {
            try
            {
                var token = Request.Cookies["Token"];

                if (string.IsNullOrEmpty(token))
                {
                    return null;
                }

                var model = new AspiranteResponseDto();
                var url = "Aspirante/GetAspiranteAsync";

                using (var client = _clientFactory.CreateClient("ApiGestionPruebas"))
                {
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                    var response = await client.GetAsync(url);
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        model = JsonSerializer.Deserialize<AspiranteResponseDto>(content);
                        return model;
                    }
                    else
                    {
                        return null;
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error en la solicitud: {ex.Message}");
                return null;
            }
        }

        [HttpGet]
        [Authorize]
        public async Task<ReporteResponseDto> GetReporteAsync()
        {
            try
            {
                var token = Request.Cookies["Token"];

                if (string.IsNullOrEmpty(token))
                {
                    return null;
                }

                var model = new ReporteResponseDto();
                var url = "Reporte/GetReporteAsync";

                using (var client = _clientFactory.CreateClient("ApiGestionPruebas"))
                {
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                    var response = await client.GetAsync(url);
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        model = JsonSerializer.Deserialize<ReporteResponseDto>(content);
                        return model;
                    }
                    else
                    {
                        return null;
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error en la solicitud: {ex.Message}");
                return null;
            }
        }


        public async Task<IActionResult> Editar(int id)
        {
            var aspiranteDto = await GetAspiranteByIdAsync(id);
            if (aspiranteDto == null)
            {
                return NotFound();
            }

            return View("Editar", aspiranteDto);
        }

        public async Task<IActionResult> Eliminar(int id)
        {
            var aspiranteDto = await GetAspiranteByIdAsync(id);
            if (aspiranteDto == null)
            {
                return NotFound();
            }

            var prueba = await DeleteAsync(aspiranteDto);
            if (prueba == null)
            {
                return NotFound();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Crear()
        {
            return View("Crear");
        }

        public async Task<IActionResult> ListAsignacionPrueba(int id)
        {
            AspirantePruebaSeleccionResponseDto model = await GetAspirantePruebaSeleccionByIdAsync(id);
            return View("AspirantePrueba", model); 
        }

        public async Task<IActionResult> AsignarPrueba()
        {
            var routeData = this.ControllerContext.RouteData.Values;

            foreach (var item in routeData)
            {
                if (item.Key == "id")
                {
                    int id = Convert.ToInt32(item.Value);
                    var aspiranteDto = await GetAspiranteByIdAsync(id);
                    if (aspiranteDto != null)
                    {
                        return View("AsignarPrueba", aspiranteDto);
                    }
                }
            }
            return NotFound();
        }


        [HttpGet]
        [Authorize]
        private async Task<AspiranteDto> GetAspiranteByIdAsync(int id)
        {
            try
            {
                var token = Request.Cookies["Token"];

                if (string.IsNullOrEmpty(token))
                {
                    return null;
                }

                var model = new AspiranteDto();
                var url = $"Aspirante/GetAspiranteByIdAsync/{id}";

                using (var client = _clientFactory.CreateClient("ApiGestionPruebas"))
                {
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                    var response = await client.GetAsync(url);
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        model = JsonSerializer.Deserialize<AspiranteDto>(content);
                        return model;
                    }
                    else
                    {
                        return null;
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error en la solicitud: {ex.Message}");
                return null;
            }
        }

        [HttpGet]
        [Authorize]
        private async Task<AspirantePruebaSeleccionResponseDto> GetAspirantePruebaSeleccionByIdAsync(int id)
        {
            try
            {
                var token = Request.Cookies["Token"];

                if (string.IsNullOrEmpty(token))
                {
                    return null;
                }

                var model = new AspirantePruebaSeleccionResponseDto();
                var url = $"AspirantePruebaSeleccion/GetAspirantePruebaSeleccionByIdAsync/{id}";

                using (var client = _clientFactory.CreateClient("ApiGestionPruebas"))
                {
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                    var response = await client.GetAsync(url);
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        model = JsonSerializer.Deserialize<AspirantePruebaSeleccionResponseDto>(content);
                        return model;
                    }
                    else
                    {
                        return null;
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error en la solicitud: {ex.Message}");
                return null;
            }
        }

        [HttpGet]
        [Authorize]
        private async Task<AspirantePruebaSeleccionDto> GetAspirantePruebaSeleccionByIdAPAsync(int id)
        {
            try
            {
                var token = Request.Cookies["Token"];

                if (string.IsNullOrEmpty(token))
                {
                    return null;
                }

                var model = new AspirantePruebaSeleccionDto();
                var url = $"AspirantePruebaSeleccion/GetAspirantePruebaSeleccionByIdAPAsync/{id}";

                using (var client = _clientFactory.CreateClient("ApiGestionPruebas"))
                {
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                    var response = await client.GetAsync(url);
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        model = JsonSerializer.Deserialize<AspirantePruebaSeleccionDto>(content);
                        return model;
                    }
                    else
                    {
                        return null;
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error en la solicitud: {ex.Message}");
                return null;
            }
        }

01. Web (UI)/GestionPruebas.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portal Selección</title>
    <link rel="stylesheet" href="https://use.typekit.net/iua0dbj.css" />
    <link href="~/css/estilo.css" rel="stylesheet" />
    <link href="~/css/inputs.css" rel="stylesheet" />
    <link href="~/css/spinkit/spinkit.min.css" rel="stylesheet" />
    <link href="~/css/toast/toast.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
    
</head>
<body>
    <div class="admin-layout">
        <nav>
            <div class="header-lista">
                <div class="separador"></div>
                <div>
                    <ul class="menu_principal">
                        <li>
                            <a class="header-link" asp-area="" asp-controller="Aspirante" asp-action="Index">
                                <span>
                                    Aspirantes
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="header-link" asp-area="" asp-controller="Seleccion" asp-action="Index">
                                <span>
                                    Pruebas Selección
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="header-link" asp-area="" asp-controller="Login" asp-action="CerrarSesion">
                                <span>
                                    Cerrar Sesión
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>


        <div class="main">
            <main role="main">
                @RenderBody()
            </main>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

01. Web (UI)/GestionPruebas.Web/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portal Selección</title>
    <base href="~/" />
    <link rel="stylesheet" href="https://use.typekit.net/iua0dbj.css" />
    <link rel="stylesheet" href="css/estilo.css" type="text/css" />
    <link rel="stylesheet" href="css/inputs.css" type="text/css" />
    <link href="GestionPruebas.Web.styles.css" rel="stylesheet">
    <link href="~/css/spinkit/spinkit.min.css" rel="stylesheet" />
    <link href="~/css/toast/toast.css" rel="stylesheet" />
    
</head>
<body>

    <div class="main">
        <div class="content px-6">
            @RenderBody()
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/powerbi-client/2.22.4/powerbi.min.js" integrity="sha512-ZMmyGjAz4cSAlJZVBrJnpcoWv2KVhPpH6H738XBYnPHY66xUC7QgmZNqBymp2WSAL3hZmdpFpVRkoB3mgET6jQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

</body>
</html>